export enum ActionType {
  FETCH_ALL = "FETCH_ALL",
  FETCH_CART = "FETCH_CART",
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  CLEAR_CART = "CLEAR_CART",
  SIGN_IN = "SIGN_IN",
  LOGOUT = "LOGOUT",
}
